apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    {{- include "stronghold.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    {{- include "stronghold.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      targetPort: http
      port: 8000
      protocol: TCP
