apiVersion: v1
kind: ServiceAccount
metadata:
  name: book-importer
  labels:
    {{- include "stronghold.labels" . | nindent 4 }}
    app.kubernetes.io/component: book-importer
  {{- with .Values.bookImporter.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.bookImporter.serviceAccount.automount }}

