apiVersion: v1
kind: ServiceAccount
metadata:
  name: feed-watcher
  labels:
    {{- include "stronghold.labels" . | nindent 4 }}
  {{- with .Values.feedWatcher.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.feedWatcher.serviceAccount.automount }}


