name: Release

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

on:
  release:
    types:
      - published

# Cancel in-progress jobs when new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-version:
    runs-on: ohnozombiesrun
    outputs:
      releaseVersion: ${{ github.event.release.name }}
      chartVersion: ${{ steps.generate-version.outputs.version }}
    steps:
      - name: generate chart version
        id: generate-version
        run: |-
          echo ${{ github.event.release.name }} | sed 's/^v//' | awk '{print "version="$1}' >> "$GITHUB_OUTPUT"

  deliver-image:
    runs-on: ohnozombiesrun
    needs:
      - generate-version
    env:
      version: ${{ needs.generate-version.outputs.releaseVersion }}
    steps:
      - name: checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          registry: ${{ secrets.DOCKER_REPO }}
          username: ${{ secrets.DOCKER_REPO_USERNAME }}
          password: ${{ secrets.DOCKER_REPO_PASSWORD }}
      - uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          push: true
          build-args: |
            VERSION=${{ env.version }}
            GIT_COMMIT=${{ github.sha }}
            BUILD_TIME=${{ github.event.release.created_at }}
          tags: |
            ${{ secrets.DOCKER_REPO_PREFIX }}/stronghold:${{ env.version }}
            ${{ secrets.DOCKER_REPO_PREFIX }}/stronghold:latest

  deliver-chart:
    runs-on: ohnozombiesrun
    needs:
      - generate-version
      - deliver-image
    steps:
      - name: checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: setup-helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1
      - run: |
          helm registry login \
            ${{ secrets.DOCKER_REPO }} \
            --username ${{ secrets.DOCKER_REPO_USERNAME }} \
            --password ${{ secrets.DOCKER_REPO_PASSWORD }}

          helm package \
            --destination . \
            --app-version ${{ needs.generate-version.outputs.releaseVersion }} \
            --version ${{ needs.generate-version.outputs.chartVersion }} \
            deploy/stronghold

          helm lint stronghold-*.tgz

          helm push \
            stronghold-*.tgz \
            oci://${{ secrets.DOCKER_REPO_PREFIX }}/charts
